class AccessoriesData {
  final String imageName;
  final String categoryName;
  final int coin;

  AccessoriesData(this.imageName, this.categoryName, this.coin);
}

class Accessories {
  final String imageName;
  final String categoryName;

  Accessories(this.imageName, this.categoryName);
}

Map<Accessories, List<AccessoriesData>> list = {
  Accessories('assets/alphabet.png', 'Alphabet'): [
    AccessoriesData('assets/camera.png', 'hat2', 100),
    AccessoriesData('assets/camera.png', 'glasses1', 100),
    AccessoriesData('assets/camera.png', 'glasses2', 100),
    AccessoriesData('assets/camera.png', 'tattoo1', 100),
    AccessoriesData('assets/camera.png', 'tattoo2', 100),
    AccessoriesData('assets/camera.png', 'earring1', 100),
    AccessoriesData('assets/camera.png', 'earring2', 100),
    AccessoriesData('assets/camera.png', 'hat1', 100),
    AccessoriesData('assets/camera.png', 'beard1', 100),
  ],
  Accessories('assets/animal.png', 'Animal'): [
    AccessoriesData('assets/camera.png', 'hat2', 100),
    AccessoriesData('assets/camera.png', 'glasses1', 100),
    AccessoriesData('assets/camera.png', 'glasses2', 100),
    AccessoriesData('assets/camera.png', 'tattoo1', 100),
    AccessoriesData('assets/camera.png', 'tattoo2', 100),
    AccessoriesData('assets/camera.png', 'earring1', 100),
    AccessoriesData('assets/camera.png', 'earring2', 100),
    AccessoriesData('assets/camera.png', 'hat1', 100),
    AccessoriesData('assets/camera.png', 'beard1', 100),
  ],
  Accessories('assets/camera.png', 'camera'): [
    AccessoriesData('assets/camera.png', 'hat2', 100),
    AccessoriesData('assets/camera.png', 'glasses1', 100),
    AccessoriesData('assets/camera.png', 'glasses2', 100),
    AccessoriesData('assets/camera.png', 'tattoo1', 100),
    AccessoriesData('assets/camera.png', 'tattoo2', 100),
    AccessoriesData('assets/camera.png', 'earring1', 100),
    AccessoriesData('assets/camera.png', 'earring2', 100),
    AccessoriesData('assets/camera.png', 'hat1', 100),
    AccessoriesData('assets/camera.png', 'beard1', 100),
  ],
  Accessories('assets/clothes.png', 'Clothes'): [
    AccessoriesData('assets/camera.png', 'hat2', 100),
    AccessoriesData('assets/camera.png', 'glasses1', 100),
    AccessoriesData('assets/camera.png', 'glasses2', 100),
    AccessoriesData('assets/camera.png', 'tattoo1', 100),
    AccessoriesData('assets/camera.png', 'tattoo2', 100),
    AccessoriesData('assets/camera.png', 'earring1', 100),
    AccessoriesData('assets/camera.png', 'earring2', 100),
    AccessoriesData('assets/camera.png', 'hat1', 100),
    AccessoriesData('assets/camera.png', 'beard1', 100),
  ],
  Accessories('assets/electronic.png', 'Electronic'): [
    AccessoriesData('assets/camera.png', 'hat2', 100),
    AccessoriesData('assets/camera.png', 'glasses1', 100),
    AccessoriesData('assets/camera.png', 'glasses2', 100),
    AccessoriesData('assets/camera.png', 'tattoo1', 100),
    AccessoriesData('assets/camera.png', 'tattoo2', 100),
    AccessoriesData('assets/camera.png', 'earring1', 100),
    AccessoriesData('assets/camera.png', 'earring2', 100),
    AccessoriesData('assets/camera.png', 'hat1', 100),
    AccessoriesData('assets/camera.png', 'beard1', 100),
  ],
  Accessories('assets/emotion.png', 'Emotions'): [
    AccessoriesData('assets/camera.png', 'hat2', 100),
    AccessoriesData('assets/camera.png', 'glasses1', 100),
    AccessoriesData('assets/camera.png', 'glasses2', 100),
    AccessoriesData('assets/camera.png', 'tattoo1', 100),
    AccessoriesData('assets/camera.png', 'tattoo2', 100),
    AccessoriesData('assets/camera.png', 'earring1', 100),
    AccessoriesData('assets/camera.png', 'earring2', 100),
    AccessoriesData('assets/camera.png', 'hat1', 100),
    AccessoriesData('assets/camera.png', 'beard1', 100),
  ],
  Accessories('assets/fruit.png', 'Fruits'): [
    AccessoriesData('assets/camera.png', 'hat2', 100),
    AccessoriesData('assets/camera.png', 'glasses1', 100),
    AccessoriesData('assets/camera.png', 'glasses2', 100),
    AccessoriesData('assets/camera.png', 'tattoo1', 100),
    AccessoriesData('assets/camera.png', 'tattoo2', 100),
    AccessoriesData('assets/camera.png', 'earring1', 100),
    AccessoriesData('assets/camera.png', 'earring2', 100),
    AccessoriesData('assets/camera.png', 'hat1', 100),
    AccessoriesData('assets/camera.png', 'beard1', 100),
  ],
  Accessories('assets/furniture.png', 'Furniture'): [
    AccessoriesData('assets/camera.png', 'hat2', 100),
    AccessoriesData('assets/camera.png', 'glasses1', 100),
    AccessoriesData('assets/camera.png', 'glasses2', 100),
    AccessoriesData('assets/camera.png', 'tattoo1', 100),
    AccessoriesData('assets/camera.png', 'tattoo2', 100),
    AccessoriesData('assets/camera.png', 'earring1', 100),
    AccessoriesData('assets/camera.png', 'earring2', 100),
    AccessoriesData('assets/camera.png', 'hat1', 100),
    AccessoriesData('assets/camera.png', 'beard1', 100),
  ],
  Accessories('assets/grains.png', 'Grains'): [
    AccessoriesData('assets/camera.png', 'hat2', 100),
    AccessoriesData('assets/camera.png', 'glasses1', 100),
    AccessoriesData('assets/camera.png', 'glasses2', 100),
    AccessoriesData('assets/camera.png', 'tattoo1', 100),
    AccessoriesData('assets/camera.png', 'tattoo2', 100),
    AccessoriesData('assets/camera.png', 'earring1', 100),
    AccessoriesData('assets/camera.png', 'earring2', 100),
    AccessoriesData('assets/camera.png', 'hat1', 100),
    AccessoriesData('assets/camera.png', 'beard1', 100),
  ],
  Accessories('assets/mic.png', 'Mic'): [
    AccessoriesData('assets/camera.png', 'hat2', 100),
    AccessoriesData('assets/camera.png', 'glasses1', 100),
    AccessoriesData('assets/camera.png', 'glasses2', 100),
    AccessoriesData('assets/camera.png', 'tattoo1', 100),
    AccessoriesData('assets/camera.png', 'tattoo2', 100),
    AccessoriesData('assets/camera.png', 'earring1', 100),
    AccessoriesData('assets/camera.png', 'earring2', 100),
    AccessoriesData('assets/camera.png', 'hat1', 100),
    AccessoriesData('assets/camera.png', 'beard1', 100),
  ],
  Accessories('assets/number.png', 'number'): [
    AccessoriesData('assets/camera.png', 'hat2', 100),
    AccessoriesData('assets/camera.png', 'glasses1', 100),
    AccessoriesData('assets/camera.png', 'glasses2', 100),
    AccessoriesData('assets/camera.png', 'tattoo1', 100),
    AccessoriesData('assets/camera.png', 'tattoo2', 100),
    AccessoriesData('assets/camera.png', 'earring1', 100),
    AccessoriesData('assets/camera.png', 'earring2', 100),
    AccessoriesData('assets/camera.png', 'hat1', 100),
    AccessoriesData('assets/camera.png', 'beard1', 100),
  ],
  Accessories('assets/stickers.png', 'stickers'): [
    AccessoriesData('assets/camera.png', 'hat2', 100),
    AccessoriesData('assets/camera.png', 'glasses1', 100),
    AccessoriesData('assets/camera.png', 'glasses2', 100),
    AccessoriesData('assets/camera.png', 'tattoo1', 100),
    AccessoriesData('assets/camera.png', 'tattoo2', 100),
    AccessoriesData('assets/camera.png', 'earring1', 100),
    AccessoriesData('assets/camera.png', 'earring2', 100),
    AccessoriesData('assets/camera.png', 'hat1', 100),
    AccessoriesData('assets/camera.png', 'beard1', 100),
  ],
  Accessories('assets/shape.png', 'Shape'): [
    AccessoriesData('assets/camera.png', 'hat2', 100),
    AccessoriesData('assets/camera.png', 'glasses1', 100),
    AccessoriesData('assets/camera.png', 'glasses2', 100),
    AccessoriesData('assets/camera.png', 'tattoo1', 100),
    AccessoriesData('assets/camera.png', 'tattoo2', 100),
    AccessoriesData('assets/camera.png', 'earring1', 100),
    AccessoriesData('assets/camera.png', 'earring2', 100),
    AccessoriesData('assets/camera.png', 'hat1', 100),
    AccessoriesData('assets/camera.png', 'beard1', 100),
  ],
  Accessories('assets/stationary.png', 'Stationary'): [
    AccessoriesData('assets/camera.png', 'hat2', 100),
    AccessoriesData('assets/camera.png', 'glasses1', 100),
    AccessoriesData('assets/camera.png', 'glasses2', 100),
    AccessoriesData('assets/camera.png', 'tattoo1', 100),
    AccessoriesData('assets/camera.png', 'tattoo2', 100),
    AccessoriesData('assets/camera.png', 'earring1', 100),
    AccessoriesData('assets/camera.png', 'earring2', 100),
    AccessoriesData('assets/camera.png', 'hat1', 100),
    AccessoriesData('assets/camera.png', 'beard1', 100),
  ],
  Accessories('assets/text.png', 'Text'): [
    AccessoriesData('assets/camera.png', 'hat2', 100),
    AccessoriesData('assets/camera.png', 'glasses1', 100),
    AccessoriesData('assets/camera.png', 'glasses2', 100),
    AccessoriesData('assets/camera.png', 'tattoo1', 100),
    AccessoriesData('assets/camera.png', 'tattoo2', 100),
    AccessoriesData('assets/camera.png', 'earring1', 100),
    AccessoriesData('assets/camera.png', 'earring2', 100),
    AccessoriesData('assets/camera.png', 'hat1', 100),
    AccessoriesData('assets/camera.png', 'beard1', 100),
  ],
  Accessories('assets/tools.png', 'Tools'): [
    AccessoriesData('assets/camera.png', 'hat2', 100),
    AccessoriesData('assets/camera.png', 'glasses1', 100),
    AccessoriesData('assets/camera.png', 'glasses2', 100),
    AccessoriesData('assets/camera.png', 'tattoo1', 100),
    AccessoriesData('assets/camera.png', 'tattoo2', 100),
    AccessoriesData('assets/camera.png', 'earring1', 100),
    AccessoriesData('assets/camera.png', 'earring2', 100),
    AccessoriesData('assets/camera.png', 'hat1', 100),
    AccessoriesData('assets/camera.png', 'beard1', 100),
  ],
};
